site_name: chalk-diagrams
site_url: https://chalk-diagrams.github.io
site_description: Chalk Diagrams - A declarative drawing API
site_author: Dan Oneață and Alexander Rush

### Repository
# repo_name: chalk-diagrams/chalk-diagrams.github.io
repo_url: https://github.com/chalk-diagrams/chalk
edit_uri: "" # comment this out to disable allowing editing of the docs from the website.
remote_branch: gh-pages
remote_name: origin

### Copyright
copyright: |
  Maintained by <a href="https://github.com/danoneata">Dan Oneață</a> and <a href="https://github.com/srush">Alexander Rush</a>.

### Preview Controls
use_directory_urls: true
strict: false
dev_addr: localhost:8000

### Configuration
docs_dir: docs

### Theme
theme:
  name: simple-blog
  include_sidebar: false
  custom_dir: docs/overrides

nav:
  - Home: index.md
  - Walkthrough:
      - Shapes: notebooks/walkthrough/shapes/notebook.md
      - Alignment: notebooks/walkthrough/alignment/notebook.md
      - Combinators: notebooks/walkthrough/combinators/notebook.md
      - Transformations: notebooks/walkthrough/transformations/notebook.md
      - Style: notebooks/walkthrough/style/notebook.md
      - Rendering: notebooks/walkthrough/rendering/notebook.md
      - Trails: notebooks/walkthrough/trails/notebook.md
      - Connections: notebooks/walkthrough/names/notebook.md
      - Broadcasting: notebooks/walkthrough/broadcast/notebook.md
  - API:
      - Diagram:
          - Alignment: api/diagram/alignment.md
          - Transformations: api/diagram/transformations.md
          - Style: api/diagram/style.md
          - Rendering: api/diagram/rendering.md
          - Subdiagram: api/diagram/subdiagram.md
          - Broadcasting: api/diagram/broadcast.md
          - Combinators: api/diagram/combinators.md
          - Arrow: api/diagram/arrow.md
          - Model: api/diagram/model.md
      - Shape: api/shapes.md
      - Combinators: api/combinators.md
      - Trail: api/trail.md
      - Path: api/path.md

  - Gallery:
      - BigBen: notebooks/examples/bigben/bigben.md
      - Hanoi: notebooks/examples/hanoi/hanoi.md
      - Koch: notebooks/examples/koch/koch.md
      - LeNet: notebooks/examples/lenet/lenet.md
      - Squares: notebooks/examples/squares/squares.md
      - Tensor: notebooks/examples/tensor/tensor.md
      - Tree: notebooks/examples/tree/tree.md
  - About:
      - about/index.md
      - License: about/license.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.magiclink
  - admonition
  - extra
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            parameter_headings: spacy
            heading_level: 4
            show_root_heading: true
            show_root_full_path: false
            show_annotations: true
            show_signature_annotations: true
## @@ End NAVIGATION
