site_name: chalk-diagrams
site_url: https://chalk-diagrams.github.io
site_description: Chalk Diagrams - A declarative drawing API
site_author: Dan Oneață and Alexander Rush

### Repository
# repo_name: chalk-diagrams/chalk-diagrams.github.io
repo_url: https://github.com/chalk-diagrams/chalk
edit_uri: "" # comment this out to disable allowing editing of the docs from the website.
remote_branch: gh-pages
remote_name: origin

### Copyright
copyright: |
  Maintained by <a href="https://github.com/danoneata">Dan Oneață</a> and <a href="https://github.com/srush">Alexander Rush</a>.

### Preview Controls
use_directory_urls: true
strict: false
dev_addr: localhost:8000

### Configuration
docs_dir: docs

# watch a list of directories for changes
# and automatically regenerate the docs
watch:
  - docs
  - walkthrough
  - examples

### Theme
theme:
  name: material
  include_sidebar: true
  custom_dir: docs/overrides

extra:
  include:
    - docs
    - walkthrough
    - examples

nav:
  - Home: README.md
  - Walkthrough:
      - Shapes: walkthrough/shapes.ipynb
      - Alignment: walkthrough/alignment.ipynb
      - Combinators: walkthrough/combinators.ipynb
      - Transformations: walkthrough/transformations.ipynb
      - Style: walkthrough/style.ipynb
      - Rendering: walkthrough/rendering.ipynb
      - Trails: walkthrough/trails.ipynb
      - Connections: walkthrough/names.ipynb
      - Broadcasting: walkthrough/broadcast.ipynb
  - API:
      - Diagram: api/diagram.md
  - Gallery:
      - BigBen: examples/output/bigben.ipynb
      - Hanoi: examples/output/hanoi.ipynb
      - Koch: examples/output/koch.ipynb
      - LeNet: examples/output/lenet.ipynb
      - Squares: examples/output/squares.ipynb
      - Tensor: examples/output/tensor.ipynb
      - Tree: examples/output/tree.ipynb
  - About:
      - about/index.md
      - License: about/license.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - admonition
  - codehilite
  - extra
plugins:
  - search
  - mkdocstrings
  - include-markdown
  - mkdocs-jupyter:
      execute: true
      include:
        - "walkthrough/*"
        - "examples/*"
      include_source: true
      ignore_h1_titles: true
## @@ End NAVIGATION
