import * as tx from "./transform.js";
import { arcSegment, path, segment } from "./geometry.js";
import { point, vec2 } from "./transform.js";

export { animate, animateScenes, frameTimes, sampleAnimation } from "./animation.js";
export {
  addShape,
  arcBetween,
  arcSegment,
  aroundCircle,
  centerOfPoints,
  centerTrail,
  circle,
  circleAt,
  circleFromArc,
  circleTrail,
  closeTrail,
  concatScenes,
  concatTrails,
  emptyScene,
  emptyTrail,
  fillColor,
  fillOpacity,
  hrule,
  lineWidth,
  locate,
  makeStyle,
  path,
  rectangle,
  regularPolygonTrail,
  resolvedArcs,
  rotateShape,
  rotateShapeBy,
  rotateTrail,
  rotateTrailBy,
  scaleShape,
  scaleTrail,
  scene,
  segment,
  shearTrailX,
  shearTrailY,
  square,
  stroke,
  strokeColor,
  strokeOpacity,
  trail,
  trailEndpoint,
  trailFromOffsets,
  trailFromPoints,
  transformShape,
  transformTrail,
  translateShape,
  translateTrail,
  triangle,
  vrule,
  type ArcSegment,
  type ResolvedArc,
  type Scene,
  type Shape,
  type ShapeStyle,
  type Trail,
} from "./geometry.js";
export {
  blockUntilReady,
  init,
  init as initJax,
  jit,
  np,
  optax,
  type JaxArray,
  type JsTree,
  valueAndGrad,
  vmap,
} from "./jax.js";
export { optimize, type OptimizeOptions, type OptimizeResult } from "./optimize.js";
export {
  boundsOfScene,
  boundsOfShape,
  centerScene,
  centerXY,
  getTrace,
  layoutScene,
  renderLineSoft,
  renderScene,
  renderShape,
  type Bounds,
  type RenderOptions,
  type TraceResult,
} from "./render.js";
export {
  EPSILON,
  TAU,
  add,
  angleOf,
  applyToPoint,
  applyToVector,
  asColor,
  asVec2,
  clamp,
  color,
  compose,
  cross2d,
  dot,
  homogeneous,
  identity,
  inverse,
  isJaxArray,
  length,
  lengthSquared,
  matrix3,
  midpoint,
  mul,
  negate,
  normalize,
  perpendicular,
  point,
  polar,
  rotation,
  rotationTurns,
  scale,
  scalar,
  shearX,
  shearY,
  sub,
  translation,
  vec2,
  wrapAngle,
  xOf,
  yOf,
  type Affine,
  type ColorLike,
  type Point,
  type ScalarLike,
  type Vec2Like,
  type Vector,
} from "./transform.js";

export { tx };

export const P2 = point;
export const V2 = vec2;
export const arcSeg = arcSegment;
export const makePath = path;
export const seg = segment;
