name: checks.yml

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt-get install libcairo2-dev
        python -m pip install --upgrade pip
        pip install -U pip wheel
        pip install -r requirements.txt -r requirements/dev.txt
    - name: Check types with pyright
      run: |
        # stop the build if there are type errors
        pyright
    - name: Make sure examples run
      run: |
        make images
    - name: Make sure docs run
      run: |
        make 
